name: "Shellcheck"
on: [push, pull_request]

jobs:
  check_script_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Shellcheck"
        run: shellcheck --check-sourced *.sh
