name: "Shellcheck"
on:
  pull_request:
  push:

jobs:
  check_script_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Shellcheck"
        run: shellcheck --check-sourced *.sh
